import { Router, type IRouter } from "express";
import academicSessionsRouter from "./academic-sessions";
import healthRouter from "./health";
import studentsRouter from "./students";
import vehiclesRouter from "./vehicles";
import tripsRouter from "./trips";
import classesRouter from "./classes";
import sectionsRouter from "./sections";
import attendanceRouter from "./attendance";
import reportsRouter from "./reports";
import settingsRouter from "./settings";
import authRouter from "./auth";
import emailRouter from "./email";
import feesRouter from "./fees";
import transportRoutesRouter from "./transport-routes";
import expendituresRouter from "./expenditures";
import teacherAuthRouter from "./teacher-auth";
import parentAuthRouter from "./parent-auth";
import teachersRouter from "./teachers";
import parentsRouter from "./parents";
import homeworkRouter from "./homework";
import marksRouter from "./marks";
import leaveRequestsRouter from "./leave-requests";
import noticesRouter from "./notices";
import timetableRouter from "./timetable";
import firRouter from "./fir";
import subjectsRouter from "./subjects";
import examsRouter from "./exams";
import examSchedulesRouter from "./exam-schedules";
import examMarksRouter from "./exam-marks";
import gradingRulesRouter from "./grading-rules";
import teacherSubjectAssignmentsRouter from "./teacher-subject-assignments";
import teacherMarkApprovalsRouter from "./teacher-mark-approvals";
import admitCardHoldsRouter from "./admit-card-holds";
import pushRouter from "./push";
import staffUsersRouter from "./staff-users";
import auditLogsRouter from "./audit-logs";
import periodsRouter from "./periods";
import websiteRouter from "./website";
import razorpayRouter from "./razorpay";
import promotionRouter from "./promotion";
import teacherAdmissionPermissionRouter from "./teacher-admission-permission";
import aiRouter from "./ai";
import teacherDocumentsRouter from "./teacher-documents";
import occasionalCollectionsRouter from "./occasional-collections";

const router: IRouter = Router();

router.use(academicSessionsRouter);
router.use(healthRouter);
router.use(studentsRouter);
router.use(vehiclesRouter);
router.use(tripsRouter);
router.use(classesRouter);
router.use(sectionsRouter);
router.use(attendanceRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(authRouter);
router.use(emailRouter);
router.use(feesRouter);
router.use(transportRoutesRouter);
router.use(expendituresRouter);
router.use(teacherAuthRouter);
router.use(parentAuthRouter);
router.use(teachersRouter);
router.use(parentsRouter);
router.use(homeworkRouter);
router.use(marksRouter);
router.use(leaveRequestsRouter);
router.use(noticesRouter);
router.use(timetableRouter);
router.use(firRouter);
router.use(subjectsRouter);
router.use(examsRouter);
router.use(examSchedulesRouter);
router.use(examMarksRouter);
router.use(gradingRulesRouter);
router.use(teacherSubjectAssignmentsRouter);
router.use(teacherMarkApprovalsRouter);
router.use(admitCardHoldsRouter);
router.use(pushRouter);
router.use(staffUsersRouter);
router.use(auditLogsRouter);
router.use(periodsRouter);
router.use(websiteRouter);
router.use(razorpayRouter);
router.use(promotionRouter);
router.use(teacherAdmissionPermissionRouter);
router.use(aiRouter);
router.use(teacherDocumentsRouter);
router.use(occasionalCollectionsRouter);

export default router;
